
server:
  tomcat:
    threads:
      max: 200 # 생성할 수 있는 thread의 총 개수
      min-spare: 10 # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 8192 # 수립가능한 connection의 총 개수
    accept-count: 100 # 작업큐의 사이즈
    connection-timeout: 20000 # timeout 판단 기준 시간, 20초
spring:
  mvc:
    async:
      request-timeout: -1
  profiles:
    default: local
  config:
    import:
      - submodule/reliable-kku-server-submodule/application-s3.yaml
      - submodule/reliable-kku-server-submodule/application-jwt.yaml
      - submodule/reliable-kku-server-submodule/application-payment.yaml
      - submodule/reliable-kku-server-submodule/application-sms.yaml
  datasource:
    hikari:
      maximum-pool-size: 50
      leak-detection-threshold: 2000
      idle-timeout: 30000
      auto-commit: true
      connection-timeout: 30000


logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
