server:
  tomcat:
    threads:
      max: 200 # 생성할 수 있는 thread의 총 개수
      min-spare: 10
    max-connections: 1024
    accept-count: 200
spring:
  jpa:
    open-in-view: false
  mvc:
    async:
      request-timeout: -1
  profiles:
    default: local
  config:
    import:
      - submodule/reliable-kku-server-submodule/application-s3.yaml
      - submodule/reliable-kku-server-submodule/application-jwt.yaml
      - submodule/reliable-kku-server-submodule/application-payment.yaml
      - submodule/reliable-kku-server-submodule/application-sms.yaml
  datasource:
    hikari:
      maximum-pool-size: 500
      leak-detection-threshold: 60000
      max-lifetime: 58000


#logging:
#  level:
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE
